CREATE TABLE PERSONAS_TEST (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100)
);

CREATE OR REPLACE PROCEDURE INSERTAR_2826_REGISTROS AS
BEGIN
    FOR i IN 1..2826 LOOP
        INSERT INTO PERSONAS_TEST (ID, NOMBRE)
        VALUES (i, 'Persona ' || i);
    END LOOP;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE ELIMINAR_2826_REGISTROS AS
BEGIN
    DELETE FROM PERSONAS_TEST;
    COMMIT;
END;
/
COMMIT;